// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UzEx.Analytics.Infrastructure;

#nullable disable

namespace UzEx.Analytics.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250828041456_BrokerPlatformKeys")]
    partial class BrokerPlatformKeys
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UzEx.Analytics.Domain.Brokers.Broker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BusinessKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("business_key");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("name");

                    b.Property<string>("NewSpotKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("new_spot_key");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("number");

                    b.Property<string>("OldSpotKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("old_spot_key");

                    b.Property<string>("RegNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("reg_number");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("region");

                    b.HasKey("Id")
                        .HasName("pk_brokers");

                    b.ToTable("brokers", (string)null);
                });

            modelBuilder.Entity("UzEx.Analytics.Domain.Calendars.Calendar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<int>("DateKey")
                        .HasColumnType("integer")
                        .HasColumnName("date_key");

                    b.HasKey("Id")
                        .HasName("pk_calendars");

                    b.HasIndex("DateKey")
                        .IsUnique()
                        .HasDatabaseName("ix_calendars_date_key");

                    b.ToTable("calendars", (string)null);
                });

            modelBuilder.Entity("UzEx.Analytics.Domain.Clients.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("address");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<string>("District")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("district");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("name");

                    b.Property<string>("NewSpotKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("new_spot_key");

                    b.Property<string>("OldSpotKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("old_spot_key");

                    b.Property<string>("RegNumber")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("reg_number");

                    b.Property<string>("Region")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("region");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_clients");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("UzEx.Analytics.Domain.Contracts.Contract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("base_price");

                    b.Property<string>("BusinessKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("business_key");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("currency");

                    b.Property<string>("DeliveryBase")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("delivery_base");

                    b.Property<int>("Form")
                        .HasColumnType("integer")
                        .HasColumnName("form");

                    b.Property<decimal>("Lot")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("lot");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("name");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("number");

                    b.Property<string>("OriginCountry")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("origin_country");

                    b.Property<int>("Platform")
                        .HasColumnType("integer")
                        .HasColumnName("platform");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("TradeType")
                        .HasColumnType("integer")
                        .HasColumnName("trade_type");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unit");

                    b.Property<string>("Warehouse")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("warehouse");

                    b.HasKey("Id")
                        .HasName("pk_contracts");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_contracts_product_id");

                    b.ToTable("contracts", (string)null);
                });

            modelBuilder.Entity("UzEx.Analytics.Domain.DataMigrations.DataMigration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<int>("DataType")
                        .HasColumnType("integer")
                        .HasColumnName("data_type");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<int>("PlatformType")
                        .HasColumnType("integer")
                        .HasColumnName("platform_type");

                    b.HasKey("Id")
                        .HasName("pk_data_migrations");

                    b.ToTable("data_migrations", (string)null);
                });

            modelBuilder.Entity("UzEx.Analytics.Domain.Deals.Deal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("amount");

                    b.Property<DateTime?>("AnnulDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("annul_date");

                    b.Property<string>("AnnulReason")
                        .HasColumnType("text")
                        .HasColumnName("annul_reason");

                    b.Property<string>("BusinessKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("business_key");

                    b.Property<Guid>("BuyerBrokerId")
                        .HasColumnType("uuid")
                        .HasColumnName("buyer_broker_id");

                    b.Property<Guid>("BuyerClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("buyer_client_id");

                    b.Property<Guid>("CalendarId")
                        .HasColumnType("uuid")
                        .HasColumnName("calendar_id");

                    b.Property<DateTime?>("CloseDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("close_date");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_id");

                    b.Property<decimal>("Cost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("cost");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<DateTime>("DateOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_on_utc");

                    b.Property<int>("DeliveryDays")
                        .HasColumnType("integer")
                        .HasColumnName("delivery_days");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_on_utc");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("number");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("payment_date");

                    b.Property<int>("PaymentDays")
                        .HasColumnType("integer")
                        .HasColumnName("payment_days");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price");

                    b.Property<Guid>("SellerBrokerId")
                        .HasColumnType("uuid")
                        .HasColumnName("seller_broker_id");

                    b.Property<Guid>("SellerClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("seller_client_id");

                    b.Property<int>("SessionType")
                        .HasColumnType("integer")
                        .HasColumnName("session_type");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_deals");

                    b.HasIndex("BuyerBrokerId")
                        .HasDatabaseName("ix_deals_buyer_broker_id");

                    b.HasIndex("BuyerClientId")
                        .HasDatabaseName("ix_deals_buyer_client_id");

                    b.HasIndex("CalendarId")
                        .HasDatabaseName("ix_deals_calendar_id");

                    b.HasIndex("ContractId")
                        .HasDatabaseName("ix_deals_contract_id");

                    b.HasIndex("SellerBrokerId")
                        .HasDatabaseName("ix_deals_seller_broker_id");

                    b.HasIndex("SellerClientId")
                        .HasDatabaseName("ix_deals_seller_client_id");

                    b.ToTable("deals", (string)null);
                });

            modelBuilder.Entity("UzEx.Analytics.Domain.Orders.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("amount");

                    b.Property<Guid>("BrokerId")
                        .HasColumnType("uuid")
                        .HasColumnName("broker_id");

                    b.Property<string>("BusinessKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("business_key");

                    b.Property<Guid>("CalendarId")
                        .HasColumnType("uuid")
                        .HasColumnName("calendar_id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_id");

                    b.Property<int>("Direction")
                        .HasColumnType("integer")
                        .HasColumnName("direction");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price");

                    b.Property<DateTime>("ReceiveDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("receive_date");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.HasIndex("BrokerId")
                        .HasDatabaseName("ix_orders_broker_id");

                    b.HasIndex("CalendarId")
                        .HasDatabaseName("ix_orders_calendar_id");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_orders_client_id");

                    b.HasIndex("ContractId")
                        .HasDatabaseName("ix_orders_contract_id");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("UzEx.Analytics.Domain.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Code")
                        .HasColumnType("integer")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("UzEx.Analytics.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("UzEx.Analytics.Domain.Calendars.Calendar", b =>
                {
                    b.OwnsOne("UzEx.Analytics.Domain.Calendars.CalendarDate", "Date", b1 =>
                        {
                            b1.Property<Guid>("CalendarId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("Day")
                                .HasColumnType("integer")
                                .HasColumnName("date_day");

                            b1.Property<int>("Month")
                                .HasColumnType("integer")
                                .HasColumnName("date_month");

                            b1.Property<int>("Year")
                                .HasColumnType("integer")
                                .HasColumnName("date_year");

                            b1.HasKey("CalendarId");

                            b1.ToTable("calendars");

                            b1.WithOwner()
                                .HasForeignKey("CalendarId")
                                .HasConstraintName("fk_calendars_calendars_id");
                        });

                    b.Navigation("Date")
                        .IsRequired();
                });

            modelBuilder.Entity("UzEx.Analytics.Domain.Contracts.Contract", b =>
                {
                    b.HasOne("UzEx.Analytics.Domain.Products.Product", "Product")
                        .WithMany("Contracts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_contracts_product_product_id");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("UzEx.Analytics.Domain.Deals.Deal", b =>
                {
                    b.HasOne("UzEx.Analytics.Domain.Brokers.Broker", "BuyerBroker")
                        .WithMany("BuyerBrokerDeals")
                        .HasForeignKey("BuyerBrokerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_deals_brokers_buyer_broker_id");

                    b.HasOne("UzEx.Analytics.Domain.Clients.Client", "BuyerClient")
                        .WithMany("BuyerDeals")
                        .HasForeignKey("BuyerClientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_deals_clients_buyer_client_id");

                    b.HasOne("UzEx.Analytics.Domain.Calendars.Calendar", "Calendar")
                        .WithMany("Deals")
                        .HasForeignKey("CalendarId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_deals_calendars_calendar_id");

                    b.HasOne("UzEx.Analytics.Domain.Contracts.Contract", "Contract")
                        .WithMany("Deals")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_deals_contracts_contract_id");

                    b.HasOne("UzEx.Analytics.Domain.Brokers.Broker", "SellerBroker")
                        .WithMany("SellerBrokerDeals")
                        .HasForeignKey("SellerBrokerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_deals_brokers_seller_broker_id");

                    b.HasOne("UzEx.Analytics.Domain.Clients.Client", "SellerClient")
                        .WithMany("SellerDeals")
                        .HasForeignKey("SellerClientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_deals_clients_seller_client_id");

                    b.Navigation("BuyerBroker");

                    b.Navigation("BuyerClient");

                    b.Navigation("Calendar");

                    b.Navigation("Contract");

                    b.Navigation("SellerBroker");

                    b.Navigation("SellerClient");
                });

            modelBuilder.Entity("UzEx.Analytics.Domain.Orders.Order", b =>
                {
                    b.HasOne("UzEx.Analytics.Domain.Brokers.Broker", "Broker")
                        .WithMany("Orders")
                        .HasForeignKey("BrokerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_orders_brokers_broker_id");

                    b.HasOne("UzEx.Analytics.Domain.Calendars.Calendar", "Calendar")
                        .WithMany("Orders")
                        .HasForeignKey("CalendarId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_orders_calendars_calendar_id");

                    b.HasOne("UzEx.Analytics.Domain.Clients.Client", "Client")
                        .WithMany("Orders")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_orders_clients_client_id");

                    b.HasOne("UzEx.Analytics.Domain.Contracts.Contract", "Contract")
                        .WithMany("Orders")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_orders_contracts_contract_id");

                    b.Navigation("Broker");

                    b.Navigation("Calendar");

                    b.Navigation("Client");

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("UzEx.Analytics.Domain.Brokers.Broker", b =>
                {
                    b.Navigation("BuyerBrokerDeals");

                    b.Navigation("Orders");

                    b.Navigation("SellerBrokerDeals");
                });

            modelBuilder.Entity("UzEx.Analytics.Domain.Calendars.Calendar", b =>
                {
                    b.Navigation("Deals");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("UzEx.Analytics.Domain.Clients.Client", b =>
                {
                    b.Navigation("BuyerDeals");

                    b.Navigation("Orders");

                    b.Navigation("SellerDeals");
                });

            modelBuilder.Entity("UzEx.Analytics.Domain.Contracts.Contract", b =>
                {
                    b.Navigation("Deals");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("UzEx.Analytics.Domain.Products.Product", b =>
                {
                    b.Navigation("Contracts");
                });
#pragma warning restore 612, 618
        }
    }
}
